export const RELICDATA = [
  {
    relic: "R1",
    carboniteCircuitBoard: 40,
    bronziumWiring: 0,
    chromiumTransistor: 0,
    aurudiumHeatsink: 0,
    electriumConductor: 0,
    zinbiddleCard: 0,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 0,
    incompleteSignalData: 0,
    flawedSignalData: 0,
  },
  {
    relic: "R2",
    carboniteCircuitBoard: 30,
    bronziumWiring: 40,
    chromiumTransistor: 0,
    aurudiumHeatsink: 0,
    electriumConductor: 0,
    zinbiddleCard: 0,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 15,
    incompleteSignalData: 0,
    flawedSignalData: 0,
  },
  {
    relic: "R3",
    carboniteCircuitBoard: 30,
    bronziumWiring: 40,
    chromiumTransistor: 20,
    aurudiumHeatsink: 0,
    electriumConductor: 0,
    zinbiddleCard: 0,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 20,
    incompleteSignalData: 15,
    flawedSignalData: 0,
  },
  {
    relic: "R4",
    carboniteCircuitBoard: 30,
    bronziumWiring: 40,
    chromiumTransistor: 40,
    aurudiumHeatsink: 0,
    electriumConductor: 0,
    zinbiddleCard: 0,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 20,
    incompleteSignalData: 25,
    flawedSignalData: 0,
  },
  {
    relic: "R5",
    carboniteCircuitBoard: 30,
    bronziumWiring: 40,
    chromiumTransistor: 30,
    aurudiumHeatsink: 20,
    electriumConductor: 0,
    zinbiddleCard: 0,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 20,
    incompleteSignalData: 25,
    flawedSignalData: 15,
  },
  {
    relic: "R6",
    carboniteCircuitBoard: 20,
    bronziumWiring: 30,
    chromiumTransistor: 30,
    aurudiumHeatsink: 20,
    electriumConductor: 20,
    zinbiddleCard: 0,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 20,
    incompleteSignalData: 25,
    flawedSignalData: 25,
  },
  {
    relic: "R7",
    carboniteCircuitBoard: 20,
    bronziumWiring: 30,
    chromiumTransistor: 20,
    aurudiumHeatsink: 20,
    electriumConductor: 20,
    zinbiddleCard: 10,
    impulseDetector: 0,
    aeromagnifier: 0,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 20,
    incompleteSignalData: 25,
    flawedSignalData: 35,
  },
  {
    relic: "R8",
    carboniteCircuitBoard: 0,
    bronziumWiring: 0,
    chromiumTransistor: 20,
    aurudiumHeatsink: 20,
    electriumConductor: 20,
    zinbiddleCard: 20,
    impulseDetector: 20,
    aeromagnifier: 20,
    gydraKeypad: 0,
    droidBrain: 0,
    fragmentedSignalData: 20,
    incompleteSignalData: 25,
    flawedSignalData: 45,
  },
  {
    relic: "R9",
    carboniteCircuitBoard: 0,
    bronziumWiring: 0,
    chromiumTransistor: 20,
    aurudiumHeatsink: 20,
    electriumConductor: 20,
    zinbiddleCard: 20,
    impulseDetector: 20,
    aeromagnifier: 20,
    gydraKeypad: 20,
    droidBrain: 20,
    fragmentedSignalData: 30,
    incompleteSignalData: 30,
    flawedSignalData: 55,
  },
];

export const RELICMATERIALIMAGES = {
  carboniteCircuitBoard: require("../images/carbonitecicuitboard.png"),
  bronziumWiring: require("../images/bronsiumwiring.png"),
  chromiumTransistor: require("../images/chromiumtransisters.png"),
  aurudiumHeatsink: require("../images/aurodiumheatsink.png"),
  electriumConductor: require("../images/electriumconductors.png"),
  zinbiddleCard: require("../images/zinbiddlecard.png"),
  impulseDetector: require("../images/impulsedetector.png"),
  aeromagnifier: require("../images/aeromagnifier.png"),
  gydraKeypad: require("../images/gyrdakeypad.png"),
  droidBrain: require("../images/droidbrain.png"),
  fragmentedSignalData: require("../images/signal_data01.png"),
  incompleteSignalData: require("../images/signal_data02.png"),
  flawedSignalData: require("../images/signal_data03.png"),
};
